### ISSUE TITLE
xstyled

### ISSUE THREAD

**Issue by yairEO** [styled-components/awesome-styled-components#120]
This is a must, a real gem:

https://www.smooth-code.com/open-source/xstyled/

**Comment by ramonfritsch** [comment]
Send a PR instead :)

**Comment by yairEO** [comment]
no time, sorry (I also see the PRs are not merged for some reason)

**Comment by kitten** [comment]
We accept PRs and not issues

**Comment by yairEO** [comment]
I don't have time for PRs I have my own open-source projects to maintain at 200% capacity, not to mention my day-job.. I wrote this quickly to simply point out that this is a super-important thing to include in your list, and you can choose to act on this information or ignore it, but by opening an issue, I did the maximum I can with my limited amount of time, sorry if this is not something you desire. I wish on my repos people would open PRs but only 1% does that.
