### ISSUE TITLE
Add more apps built with s-c

### ISSUE THREAD

**Issue by mxstbr** [styled-components/awesome-styled-components#86]
We should add all these apps to the "Real Apps" section: https://github.com/styled-components/styled-components-website/issues/275

**Comment by ayoola-solomon** [comment]
I will make a pull request soon 💯

**Comment by ayoola-solomon** [comment]
@mxstbr https://github.com/styled-components/awesome-styled-components/pull/87 waiting to be reviewed.

**Comment by themgoncalves** [comment]
@mxstbr shouldn't this `issue` be marked as resolved? Since the #87 was merged?
